apiVersion: v1
kind: ConfigMap
metadata: 
  name: frontend
  namespace: expense
data:
  DB_HOST: mysql  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: manikantarouthu/frontend:v1.0
        envFrom: 
        - configMapRef:
            name: frontend

---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: expense
    tier: web
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
